/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppStockMovementsRouteImport } from './routes/app.stock-movements'
import { Route as AppStockAdjustRouteImport } from './routes/app.stock-adjust'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSalesRouteImport } from './routes/app.sales'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPurchasesRouteImport } from './routes/app.purchases'
import { Route as AppProfitsRouteImport } from './routes/app.profits'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppPrinterRouteImport } from './routes/app.printer'
import { Route as AppPosRouteImport } from './routes/app.pos'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppDriverRouteImport } from './routes/app.driver'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppCashRouteImport } from './routes/app.cash'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppActivateRouteImport } from './routes/app.activate'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as AppTrucksIndexRouteImport } from './routes/app.trucks.index'
import { Route as AppSalesIndexRouteImport } from './routes/app.sales.index'
import { Route as AppTrucksTruckIdRouteImport } from './routes/app.trucks.$truckId'
import { Route as AppSalesSaleIdRouteImport } from './routes/app.sales.$saleId'
import { Route as AppPurchasesNewRouteImport } from './routes/app.purchases.new'
import { Route as AppSalesSaleIdIndexRouteImport } from './routes/app.sales.$saleId.index'
import { Route as AppSalesSaleIdPrintRouteImport } from './routes/app.sales.$saleId.print'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppStockMovementsRoute = AppStockMovementsRouteImport.update({
  id: '/stock-movements',
  path: '/stock-movements',
  getParentRoute: () => AppRoute,
} as any)
const AppStockAdjustRoute = AppStockAdjustRouteImport.update({
  id: '/stock-adjust',
  path: '/stock-adjust',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppProfitsRoute = AppProfitsRouteImport.update({
  id: '/profits',
  path: '/profits',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPrinterRoute = AppPrinterRouteImport.update({
  id: '/printer',
  path: '/printer',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDriverRoute = AppDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCashRoute = AppCashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppActivateRoute = AppActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppTrucksIndexRoute = AppTrucksIndexRouteImport.update({
  id: '/trucks/',
  path: '/trucks/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppTrucksTruckIdRoute = AppTrucksTruckIdRouteImport.update({
  id: '/trucks/$truckId',
  path: '/trucks/$truckId',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesSaleIdRoute = AppSalesSaleIdRouteImport.update({
  id: '/$saleId',
  path: '/$saleId',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppPurchasesNewRoute = AppPurchasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPurchasesRoute,
} as any)
const AppSalesSaleIdIndexRoute = AppSalesSaleIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesSaleIdRoute,
} as any)
const AppSalesSaleIdPrintRoute = AppSalesSaleIdPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => AppSalesSaleIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/account': typeof AppAccountRoute
  '/app/activate': typeof AppActivateRoute
  '/app/admin': typeof AppAdminRoute
  '/app/cash': typeof AppCashRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/driver': typeof AppDriverRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/pos': typeof AppPosRoute
  '/app/printer': typeof AppPrinterRoute
  '/app/products': typeof AppProductsRoute
  '/app/profits': typeof AppProfitsRoute
  '/app/purchases': typeof AppPurchasesRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/stock-adjust': typeof AppStockAdjustRoute
  '/app/stock-movements': typeof AppStockMovementsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/': typeof AppIndexRoute
  '/app/purchases/new': typeof AppPurchasesNewRoute
  '/app/sales/$saleId': typeof AppSalesSaleIdRouteWithChildren
  '/app/trucks/$truckId': typeof AppTrucksTruckIdRoute
  '/app/sales/': typeof AppSalesIndexRoute
  '/app/trucks/': typeof AppTrucksIndexRoute
  '/app/sales/$saleId/print': typeof AppSalesSaleIdPrintRoute
  '/app/sales/$saleId/': typeof AppSalesSaleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/account': typeof AppAccountRoute
  '/app/activate': typeof AppActivateRoute
  '/app/admin': typeof AppAdminRoute
  '/app/cash': typeof AppCashRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/driver': typeof AppDriverRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/pos': typeof AppPosRoute
  '/app/printer': typeof AppPrinterRoute
  '/app/products': typeof AppProductsRoute
  '/app/profits': typeof AppProfitsRoute
  '/app/purchases': typeof AppPurchasesRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stock-adjust': typeof AppStockAdjustRoute
  '/app/stock-movements': typeof AppStockMovementsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app': typeof AppIndexRoute
  '/app/purchases/new': typeof AppPurchasesNewRoute
  '/app/trucks/$truckId': typeof AppTrucksTruckIdRoute
  '/app/sales': typeof AppSalesIndexRoute
  '/app/trucks': typeof AppTrucksIndexRoute
  '/app/sales/$saleId/print': typeof AppSalesSaleIdPrintRoute
  '/app/sales/$saleId': typeof AppSalesSaleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/account': typeof AppAccountRoute
  '/app/activate': typeof AppActivateRoute
  '/app/admin': typeof AppAdminRoute
  '/app/cash': typeof AppCashRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/driver': typeof AppDriverRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/pos': typeof AppPosRoute
  '/app/printer': typeof AppPrinterRoute
  '/app/products': typeof AppProductsRoute
  '/app/profits': typeof AppProfitsRoute
  '/app/purchases': typeof AppPurchasesRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/stock-adjust': typeof AppStockAdjustRoute
  '/app/stock-movements': typeof AppStockMovementsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/': typeof AppIndexRoute
  '/app/purchases/new': typeof AppPurchasesNewRoute
  '/app/sales/$saleId': typeof AppSalesSaleIdRouteWithChildren
  '/app/trucks/$truckId': typeof AppTrucksTruckIdRoute
  '/app/sales/': typeof AppSalesIndexRoute
  '/app/trucks/': typeof AppTrucksIndexRoute
  '/app/sales/$saleId/print': typeof AppSalesSaleIdPrintRoute
  '/app/sales/$saleId/': typeof AppSalesSaleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/account'
    | '/app/activate'
    | '/app/admin'
    | '/app/cash'
    | '/app/customers'
    | '/app/driver'
    | '/app/expenses'
    | '/app/finance'
    | '/app/inventory'
    | '/app/pos'
    | '/app/printer'
    | '/app/products'
    | '/app/profits'
    | '/app/purchases'
    | '/app/reports'
    | '/app/sales'
    | '/app/settings'
    | '/app/stock-adjust'
    | '/app/stock-movements'
    | '/app/suppliers'
    | '/app/'
    | '/app/purchases/new'
    | '/app/sales/$saleId'
    | '/app/trucks/$truckId'
    | '/app/sales/'
    | '/app/trucks/'
    | '/app/sales/$saleId/print'
    | '/app/sales/$saleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/account'
    | '/app/activate'
    | '/app/admin'
    | '/app/cash'
    | '/app/customers'
    | '/app/driver'
    | '/app/expenses'
    | '/app/finance'
    | '/app/inventory'
    | '/app/pos'
    | '/app/printer'
    | '/app/products'
    | '/app/profits'
    | '/app/purchases'
    | '/app/reports'
    | '/app/settings'
    | '/app/stock-adjust'
    | '/app/stock-movements'
    | '/app/suppliers'
    | '/app'
    | '/app/purchases/new'
    | '/app/trucks/$truckId'
    | '/app/sales'
    | '/app/trucks'
    | '/app/sales/$saleId/print'
    | '/app/sales/$saleId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/account'
    | '/app/activate'
    | '/app/admin'
    | '/app/cash'
    | '/app/customers'
    | '/app/driver'
    | '/app/expenses'
    | '/app/finance'
    | '/app/inventory'
    | '/app/pos'
    | '/app/printer'
    | '/app/products'
    | '/app/profits'
    | '/app/purchases'
    | '/app/reports'
    | '/app/sales'
    | '/app/settings'
    | '/app/stock-adjust'
    | '/app/stock-movements'
    | '/app/suppliers'
    | '/app/'
    | '/app/purchases/new'
    | '/app/sales/$saleId'
    | '/app/trucks/$truckId'
    | '/app/sales/'
    | '/app/trucks/'
    | '/app/sales/$saleId/print'
    | '/app/sales/$saleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stock-movements': {
      id: '/app/stock-movements'
      path: '/stock-movements'
      fullPath: '/app/stock-movements'
      preLoaderRoute: typeof AppStockMovementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stock-adjust': {
      id: '/app/stock-adjust'
      path: '/stock-adjust'
      fullPath: '/app/stock-adjust'
      preLoaderRoute: typeof AppStockAdjustRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales': {
      id: '/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchases': {
      id: '/app/purchases'
      path: '/purchases'
      fullPath: '/app/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profits': {
      id: '/app/profits'
      path: '/profits'
      fullPath: '/app/profits'
      preLoaderRoute: typeof AppProfitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/printer': {
      id: '/app/printer'
      path: '/printer'
      fullPath: '/app/printer'
      preLoaderRoute: typeof AppPrinterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pos': {
      id: '/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/driver': {
      id: '/app/driver'
      path: '/driver'
      fullPath: '/app/driver'
      preLoaderRoute: typeof AppDriverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cash': {
      id: '/app/cash'
      path: '/cash'
      fullPath: '/app/cash'
      preLoaderRoute: typeof AppCashRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activate': {
      id: '/app/activate'
      path: '/activate'
      fullPath: '/app/activate'
      preLoaderRoute: typeof AppActivateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trucks/': {
      id: '/app/trucks/'
      path: '/trucks'
      fullPath: '/app/trucks/'
      preLoaderRoute: typeof AppTrucksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales/': {
      id: '/app/sales/'
      path: '/'
      fullPath: '/app/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/app/trucks/$truckId': {
      id: '/app/trucks/$truckId'
      path: '/trucks/$truckId'
      fullPath: '/app/trucks/$truckId'
      preLoaderRoute: typeof AppTrucksTruckIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales/$saleId': {
      id: '/app/sales/$saleId'
      path: '/$saleId'
      fullPath: '/app/sales/$saleId'
      preLoaderRoute: typeof AppSalesSaleIdRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/app/purchases/new': {
      id: '/app/purchases/new'
      path: '/new'
      fullPath: '/app/purchases/new'
      preLoaderRoute: typeof AppPurchasesNewRouteImport
      parentRoute: typeof AppPurchasesRoute
    }
    '/app/sales/$saleId/': {
      id: '/app/sales/$saleId/'
      path: '/'
      fullPath: '/app/sales/$saleId/'
      preLoaderRoute: typeof AppSalesSaleIdIndexRouteImport
      parentRoute: typeof AppSalesSaleIdRoute
    }
    '/app/sales/$saleId/print': {
      id: '/app/sales/$saleId/print'
      path: '/print'
      fullPath: '/app/sales/$saleId/print'
      preLoaderRoute: typeof AppSalesSaleIdPrintRouteImport
      parentRoute: typeof AppSalesSaleIdRoute
    }
  }
}

interface AppPurchasesRouteChildren {
  AppPurchasesNewRoute: typeof AppPurchasesNewRoute
}

const AppPurchasesRouteChildren: AppPurchasesRouteChildren = {
  AppPurchasesNewRoute: AppPurchasesNewRoute,
}

const AppPurchasesRouteWithChildren = AppPurchasesRoute._addFileChildren(
  AppPurchasesRouteChildren,
)

interface AppSalesSaleIdRouteChildren {
  AppSalesSaleIdPrintRoute: typeof AppSalesSaleIdPrintRoute
  AppSalesSaleIdIndexRoute: typeof AppSalesSaleIdIndexRoute
}

const AppSalesSaleIdRouteChildren: AppSalesSaleIdRouteChildren = {
  AppSalesSaleIdPrintRoute: AppSalesSaleIdPrintRoute,
  AppSalesSaleIdIndexRoute: AppSalesSaleIdIndexRoute,
}

const AppSalesSaleIdRouteWithChildren = AppSalesSaleIdRoute._addFileChildren(
  AppSalesSaleIdRouteChildren,
)

interface AppSalesRouteChildren {
  AppSalesSaleIdRoute: typeof AppSalesSaleIdRouteWithChildren
  AppSalesIndexRoute: typeof AppSalesIndexRoute
}

const AppSalesRouteChildren: AppSalesRouteChildren = {
  AppSalesSaleIdRoute: AppSalesSaleIdRouteWithChildren,
  AppSalesIndexRoute: AppSalesIndexRoute,
}

const AppSalesRouteWithChildren = AppSalesRoute._addFileChildren(
  AppSalesRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppActivateRoute: typeof AppActivateRoute
  AppAdminRoute: typeof AppAdminRoute
  AppCashRoute: typeof AppCashRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDriverRoute: typeof AppDriverRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppPosRoute: typeof AppPosRoute
  AppPrinterRoute: typeof AppPrinterRoute
  AppProductsRoute: typeof AppProductsRoute
  AppProfitsRoute: typeof AppProfitsRoute
  AppPurchasesRoute: typeof AppPurchasesRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppStockAdjustRoute: typeof AppStockAdjustRoute
  AppStockMovementsRoute: typeof AppStockMovementsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTrucksTruckIdRoute: typeof AppTrucksTruckIdRoute
  AppTrucksIndexRoute: typeof AppTrucksIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppActivateRoute: AppActivateRoute,
  AppAdminRoute: AppAdminRoute,
  AppCashRoute: AppCashRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDriverRoute: AppDriverRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppPosRoute: AppPosRoute,
  AppPrinterRoute: AppPrinterRoute,
  AppProductsRoute: AppProductsRoute,
  AppProfitsRoute: AppProfitsRoute,
  AppPurchasesRoute: AppPurchasesRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppStockAdjustRoute: AppStockAdjustRoute,
  AppStockMovementsRoute: AppStockMovementsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppIndexRoute: AppIndexRoute,
  AppTrucksTruckIdRoute: AppTrucksTruckIdRoute,
  AppTrucksIndexRoute: AppTrucksIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
